apiVersion: v1
kind: ServiceAccount
metadata:
  name: rjmx-exporter
  labels:
    app: rjmx-exporter
    app.kubernetes.io/name: rjmx-exporter
    app.kubernetes.io/component: metrics-exporter
automountServiceAccountToken: false
