apiVersion: v1
kind: Service
metadata:
  name: rjmx-exporter
  labels:
    app: rjmx-exporter
    app.kubernetes.io/name: rjmx-exporter
    app.kubernetes.io/component: metrics-exporter
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9090
      targetPort: http-metrics
      protocol: TCP
  selector:
    app: rjmx-exporter
