# docker/prometheus/prometheus.yml
#
# Prometheus configuration for testing rJMX-Exporter

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape rJMX-Exporter
  - job_name: "rjmx-exporter"
    static_configs:
      - targets: ["host.docker.internal:9090"]
    metrics_path: /metrics

  # Scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
