{{- if .Values.jolokiaAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rjmx-exporter.secretName" . }}
  labels:
    {{- include "rjmx-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.jolokiaAuth.username | b64enc | quote }}
  password: {{ .Values.jolokiaAuth.password | b64enc | quote }}
{{- end }}
